name: BlobStore-Test

on:
  push:
    paths:
        - 'blobstore/**.go'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
        - 'blobstore/**'

jobs:
  GolangTest:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go Version 1.17.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make compiled rocksdb includes
        run: |
          cd blobstore
          wget -O deps.tar.gz https://ocs-cn-south1.heytapcs.com/blobstore/deps.tar.gz
          tar -zxf deps.tar.gz
          mv deps .deps
          source env.sh
          echo "CGO_CFLAGS=${CGO_CFLAGS}" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=${CGO_LDFLAGS}" >> $GITHUB_ENV

      - name: Check and Verify Go modules
        run: |
          cd blobstore
          go mod tidy -go=1.17
          git diff --exit-code go.mod go.sum
          go mod verify

      - name: Go test with coverage
        run: |
          cd blobstore
          go test -trimpath -covermode=count --coverprofile coverage.txt ./...
        env:
          JENKINS_TEST: TRUE

      # - name: Upload codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./blobstore/coverage.txt
