name: BlobStore-Format

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  GolangFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go Version 1.17.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make compiled rocksdb includes
        run: |
          cd blobstore
          wget -O deps.tar.gz http://ocs-upload-cn.heytapcs.com/deps.tar.gz
          tar -zxf deps.tar.gz
          mv deps .deps
          source env.sh
          echo "CGO_CFLAGS=${CGO_CFLAGS}" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=${CGO_LDFLAGS}" >> $GITHUB_ENV

      - name: Check golang vet
        run: |
          cd blobstore
          go vet -trimpath ./...

      - name: Go code format with gofumpt
        run: |
          cd blobstore
          go install mvdan.cc/gofumpt@v0.2.1
          gofumpt -l -w .
          git diff --exit-code
